//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesajlasma_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupUyeleri
    {
        public int grupUyeId { get; set; }
        public int grupId { get; set; }
        public int uyeId { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public string UyeAdi { get; internal set; }
    }
}
