//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesajlasma_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int mesajId { get; set; }
        public string icerik { get; set; }
        public System.DateTime mesajTarihi { get; set; }
        public int gonderenId { get; set; }
        public Nullable<int> aliciId { get; set; }
        public Nullable<int> grupId { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
    }
}
