//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesajlasma_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopluMesajlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopluMesajlar()
        {
            this.TopluMesajAlicilar = new HashSet<TopluMesajAlicilar>();
        }
    
        public int mesajId { get; set; }
        public string icerik { get; set; }
        public System.DateTime mesajTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopluMesajAlicilar> TopluMesajAlicilar { get; set; }
    }
}
