//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesajlasma_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopluMesajAlicilar
    {
        public int id { get; set; }
        public int mesajId { get; set; }
        public int aliciId { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual TopluMesajlar TopluMesajlar { get; set; }
    }
}
